 ### ndarray与Python原生list运算效率对比

In [1]:
import random
import time
import numpy as np
from IPython.core.completerlib import import_re

a = []
for i in range(100000000):
    a.append(random.random())
t1 = time.time()
sum1 = sum(a)
t2 = time.time()
b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2- t1, t5- t4)

0.3714413642883301 0.0463712215423584


Numpy（Numerical Python）是一个开源的Python科学计算库，用于快速处理任意维度的数组。
Numpy支持常见的数组和矩阵操作。对于同样的数值计算任务，使用Numpy比直接使用Python要简洁的多。
Numpy使用ndarray对象来处理多维数组，该对象是一个快速而灵活的大数据容器。
优点：
1. 快速，性能好
2. 方便
3. 科学计算的基础库
4. 对于同样的数值计算任务，使用NumPy要比直接编写Python代码便捷得多；
5. NumPy中的数组的存储效率和输入输出性能均远远优于Python中等价的基本数据结构，且其能够提升的性能是与数组中的元素成比例的；
6. NumPy的大部分代码都是用C语言写的，其底层算法在设计时就有着优异的性能，这使得NumPy比纯Python代码高效得多

### NumPy的Ndarray对象

#### 1.创建一维数组

In [2]:
import numpy as np
list1=[1,2,3,4]
oneArray=np.array(list1)
print(type(oneArray))
print(oneArray)

<class 'numpy.ndarray'>
[1 2 3 4]


In [4]:
import numpy as np
# 创建数组的多种形式
#1.直接传入列表的方式
t1=np.array([1,2,3])
print(t1)
print(type(t1))

#2.传入range生成序列
t2 = np.array(range(10))
print(t2)
print(type(t2))

#3.使用numpy自带的np.arange()生成数组
t3=np.arange(0,10,2)
print(t3)
print(type(t3))


[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 2 4 6 8]
<class 'numpy.ndarray'>


#### 2.创建二维数组

In [1]:
import numpy as np
list2=[[1,2],[3,4],[5,6]]
twoArray=np.array(list2)
print(twoArray)

[[1 2]
 [3 4]
 [5 6]]


#### 3.常用属性

In [2]:
list2=[[1,2],[3,4],[5,6]]
twoArray=np.array(list2)
#获取数组的维度(注意：与函数的参数很像)
print(twoArray.ndim)
#形状（行，列）
print(twoArray.shape)
#有多少个元素
print(twoArray.size)

2
(3, 2)
6


#### 4.调整数组形状

In [4]:
four=np.array([[1,2,3],[4,5,6]])
#修改的是原有的
four.shape=(3,2)
print(four)

#返回一个新的数组
four=four.reshape(3,2)
print(four)

#将多维变成一维数组
five=four.reshape((6,),order='F')
#默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six=four.flatten(order='C')
print(five)
print(six)

#拓展：数组的形状
t=np.arange(24)
print(t)
print(t.shape)

#转换成二维
t1=t.reshape((4,6))
print(t1)
print(t1.shape)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 3 5 2 4 6]
[1 2 3 4 5 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


#### 5.将数组转成list

In [5]:
#将数组转成list
a=np.array([9,12,88,14,25])
list_a=a.tolist()
print(list_a)
print(type(list_a))

[9, 12, 88, 14, 25]
<class 'list'>


#### 6.numpy的数据类型

In [7]:
import random
#返回数组中每个元素的字节单位长度，dtype设置数据类型
f=np.array([1,2,3,4,5],dtype=np.int16)
print(f.itemsize)#1np.int8(一个字节) 数组中每个元素占用的字节数，16位整数 = 2字节，输出为字节数
#获取数据类型
print(f.dtype)
#调整数据类型
f1=f.astype(np.int64)
print(f1.dtype)
#拓展随机生成小数
#使用python语法，保留两位
print(round(random.random(),2))
arr=np.array([random.random()for i in range(10)])
print(arr)
#取小数点后两位
print(np.round(arr,2))

2
int16
int64
0.65
[0.06874044 0.96012969 0.58222096 0.93566997 0.36904923 0.78576463
 0.87025091 0.21128088 0.37589018 0.85954322]
[0.07 0.96 0.58 0.94 0.37 0.79 0.87 0.21 0.38 0.86]
