 ### ndarray与Python原生list运算效率对比

In [1]:
import random
import time
import numpy as np
from IPython.core.completerlib import import_re
from fontTools.varLib.instancer import axisValuesFromAxisLimits

a = []
for i in range(100000000):
    a.append(random.random())
t1 = time.time()
sum1 = sum(a)
t2 = time.time()
b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2- t1, t5- t4)

0.3714413642883301 0.0463712215423584


Numpy（Numerical Python）是一个开源的Python科学计算库，用于快速处理任意维度的数组。
Numpy支持常见的数组和矩阵操作。对于同样的数值计算任务，使用Numpy比直接使用Python要简洁的多。
Numpy使用ndarray对象来处理多维数组，该对象是一个快速而灵活的大数据容器。
优点：
1. 快速，性能好
2. 方便
3. 科学计算的基础库
4. 对于同样的数值计算任务，使用NumPy要比直接编写Python代码便捷得多；
5. NumPy中的数组的存储效率和输入输出性能均远远优于Python中等价的基本数据结构，且其能够提升的性能是与数组中的元素成比例的；
6. NumPy的大部分代码都是用C语言写的，其底层算法在设计时就有着优异的性能，这使得NumPy比纯Python代码高效得多

### NumPy的Ndarray对象

#### 1.创建一维数组

In [2]:
import numpy as np
list1=[1,2,3,4]
oneArray=np.array(list1)
print(type(oneArray))
print(oneArray)

<class 'numpy.ndarray'>
[1 2 3 4]


In [4]:
import numpy as np
# 创建数组的多种形式
#1.直接传入列表的方式
t1=np.array([1,2,3])
print(t1)
print(type(t1))

#2.传入range生成序列
t2 = np.array(range(10))
print(t2)
print(type(t2))

#3.使用numpy自带的np.arange()生成数组
t3=np.arange(0,10,2)
print(t3)
print(type(t3))


[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 2 4 6 8]
<class 'numpy.ndarray'>


#### 2.创建二维数组

In [1]:
import numpy as np
list2=[[1,2],[3,4],[5,6]]
twoArray=np.array(list2)
print(twoArray)

[[1 2]
 [3 4]
 [5 6]]


#### 3.常用属性

In [2]:
list2=[[1,2],[3,4],[5,6]]
twoArray=np.array(list2)
#获取数组的维度(注意：与函数的参数很像)
print(twoArray.ndim)
#形状（行，列）
print(twoArray.shape)
#有多少个元素
print(twoArray.size)

2
(3, 2)
6


#### 4.调整数组形状

In [4]:
four=np.array([[1,2,3],[4,5,6]])
#修改的是原有的
four.shape=(3,2)
print(four)

#返回一个新的数组
four=four.reshape(3,2)
print(four)

#将多维变成一维数组
five=four.reshape((6,),order='F')
#默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six=four.flatten(order='C')
print(five)
print(six)

#拓展：数组的形状
t=np.arange(24)
print(t)
print(t.shape)

#转换成二维
t1=t.reshape((4,6))
print(t1)
print(t1.shape)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 3 5 2 4 6]
[1 2 3 4 5 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


#### 5.将数组转成list

In [5]:
#将数组转成list
a=np.array([9,12,88,14,25])
list_a=a.tolist()
print(list_a)
print(type(list_a))

[9, 12, 88, 14, 25]
<class 'list'>


#### 6.numpy的数据类型

In [8]:
import random
#返回数组中每个元素的字节单位长度，dtype设置数据类型
f=np.array([1,2,3,4,5],dtype=np.int16)
print(f.itemsize)#1np.int8(一个字节) 数组中每个元素占用的字节数，16位整数 = 2字节，输出为字节数
#获取数据类型
print(f.dtype)
#调整数据类型
f1=f.astype(np.int64)
print(f1.dtype)
#拓展随机生成小数
#使用python语法，保留两位
print(round(random.random(),2))
arr=np.array([random.random()for i in range(10)])
print(arr)
#取小数点后两位
print(np.round(arr,2))

2
int16
int64
0.12
[0.44074422 0.27519135 0.99192595 0.22119035 0.30949193 0.1882589
 0.34125309 0.18826278 0.51148465 0.97998886]
[0.44 0.28 0.99 0.22 0.31 0.19 0.34 0.19 0.51 0.98]


### 数组的计算

#### 1.数组和数的计算

In [9]:
t1=np.arange(24).reshape((6,4))
print(t1+2)
print("-"*20)
print(t1*2)
print("-"*20)
print(t1/2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


#### 2.数组与数组之间的操作

In [14]:
# 同种形状的数组(对应位置进行计算操作
# 不种形状的多维数组不能计算
t1=np.arange(24).reshape((6,4))
print(t1)
print("-"*20)
print(t2)
print("-"*20)
t2=np.arange(100,124).reshape((6,4))
print(t1+t2)
print("-"*20)
print(t1*t2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [15]:
# 行数或者列数相同的一维数组和多维数组可以进行计算
t1 =np.arange(24).reshape((4,6))
t2 = np.arange(0,6)
print(t1)
print("-"*20)
print(t2)
print("-"*20)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[0 1 2 3 4 5]
--------------------
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [16]:
# 行形状相同（会与每一行数组的对应位相操作)
t1 =np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1)
print("-"*20)
print(t2)
print("-"*20)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[[0]
 [1]
 [2]
 [3]]
--------------------
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


#### 3.数组中的轴

- 什么是轴：在numpy中可以理解为方向，使用0，1，2数字表示，对于一个一维数组，只有一个0轴， 对于2维数组（shape（2，2))有0轴和1轴，对于3维数组（shape（2，2，3））有0，1，2轴
- 为什么要学习轴：有了轴的概念后，我们计算会更加方便，比如计算一个2维数组的平均值，必须指定是计算哪个方向上面的数字的平均值。

In [18]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a,axis=0)) # [5 7 9]
print(np.sum(a,axis = 1)) # [ 6 15]
print(np.sum(a))

[5 7 9]
[ 6 15]
21


In [19]:
a=np.arange(27).reshape((3,3,3))
print(a)
# b[0,0] = a[0,0,0] + a[1,0,0] + a[2,0,0] = 0 + 9 + 18 = 27
# b[0,1] = a[0,0,1] + a[1,0,1] + a[2,0,1] = 1 + 10 + 19 = 30
# b[0,2] = a[0,0,2] + a[1,0,2] + a[2,0,2] = 2 + 11 + 20 = 33
b=np.sum(a, axis=0)
print("-"*20)
# c[0,0] = a[0,0,0] + a[0,1,0] + a[0,2,0] = 0 + 3 + 6 = 9
# c[0,1] = a[0,0,1] + a[0,1,1] + a[0,2,1] = 1 + 4 + 7 = 12
# c[0,2] = a[0,0,2] + a[0,1,2] + a[0,2,2] = 2 + 5 + 8 = 15
print(b)
c=np.sum(a, axis=1)
print("-"*20)
# d[0,0] = a[0,0,0] + a[0,0,1] + a[0,0,2] = 0 + 1 + 2 = 3
# d[0,1] = a[0,1,0] + a[0,1,1] + a[0,1,2] = 3 + 4 + 5 = 12
# d[0,2] = a[0,2,0] + a[0,2,1] + a[0,2,2] = 6 + 7 + 8 = 21
print(c)
d=np.sum(a, axis=2)
print("-"*20)
print(d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]
--------------------
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
--------------------
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


In [20]:
# 看形状，选那轴就不要
import numpy as np
a=np.arange(24).reshape((2,3,4))
b=np.sum(a, axis=0)
print("-"*20)
print(b.shape)
c=np.sum(a, axis=1)
print("-"*20)
print(c.shape)
d=np.sum(a, axis=2)
print("-"*20)
print(d.shape)

--------------------
(3, 4)
--------------------
(2, 4)
--------------------
(2, 3)


###  数组的索引和切片

In [21]:
import numpy as np

a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2
# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2],a)
# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


### 多维数组的操作方法

In [22]:
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)

print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的)print(t1[1,:]) # 取一行
print('*'*20)

print(t1[1:])# 取连续的多行
print('*'*20)

print(t1[1:3,:])# 取连续的多行
print('*'*20)

print(t1[[0,2,3]])# 取不连续的多行
print('*'*20)

print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)

print(t1[:,1])# 取一列
print('*'*20)

print(t1[:,1:])# 连续的多列
print('*'*20)

print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)

print(t1[2,3])# # 取某一个值,三行四列
print('*'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************


 #### 数组中的数值修改

In [25]:
import numpy as np
t = np.arange( 24 ).reshape( 4, 6 )
# # 修改某一行的值
t[1, :] = 0
print(t)
print('*'*20)

# # 修改某一列的值
t[:, 1] = 0
print(t)
print('*'*20)

# # 修改连续多行
t[1:3, :] = 0
print(t)
print('*'*20)

# # 修改连续多列
t[:, 1:4] = 0
print('*'*20)

# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:4,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[0,3]]=0
# print(t)
# 可以根据条件修改，比如讲小于10的值改掉
t[t < 10] = 0
# print(t)
# 使用逻辑判断
# np.logical_and & # np.logical_or |
# np.logical_not~
t[(t > 2) & (t < 6)] = 0 # 与
t[(t < 2) | (t > 6)] = 0 # 或
t[~(t > 6)] = 0 # 非
print(t)

t=t.clip(10,18)
print(t)
print('*'*20)
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array( [[80, 88], [82, 81], [75, 81]] )
result = np.where(score > 80, True, False )
print(result)

[[ 0  1  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  0  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12  0 14 15 16 17]
 [18  0 20 21 22 23]]
********************
[[ 0  0  2  3  4  5]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0 20 21 22 23]]
********************
********************
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
********************
[[False  True]
 [ True  True]
 [False  True]]


#### 数组的添加、删除和去重

##### 1.数组的添加

In [26]:
 #数组的添加
# 1. numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。
# 此外，输入数组的维度必须匹配否则将生成ValueError。
'''
参 数 说明：
arr： 输 入 数 组
values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）
axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！当axis有定义的
时候，分别为0和1的时候。当
axis 有定义的时候，分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边
（行数要相同）
'''
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')
print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))
print('\n')
print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [28]:
# 2. numpy.insert
# 函数在给定索引之前，沿给定轴在输入数组中插入值。
# 如果值的类型转换为要插入，则它与输入数组不同。
# 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。
a = np.array([[1, 2], [3, 4], [5, 6]])
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 3, [11, 12]))
print('\n')
print('传递了 Axis 参数。 会广播值数组来配输入数组。')
print('沿轴 0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')
print('沿轴 1 广播：')
print(np.insert(a, 1, 11, axis=1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


##### 2.数组中的删除

In [29]:
#numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
# 如果未提供轴参数， 则输入数组将展开。
'''
参 数 说明：arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组axis：
沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开
'''
import numpy as np
a = np.arange(12).reshape(3,4)
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a,5))
print('\n')
print('删除每一行中的第二列：')
print(np.delete(a,1,axis = 1))
print('\n')

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除每一行中的第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




##### 3.数组去重

In [30]:
# numpy.unique 函数用于去除数组中的重复元素。
'''
arr：输入数组，如果不是一维数组则会展开
return_index：如果为 true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为 true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为 true，返回去重数组中的元素在原数组中的出现次数
'''
import numpy as np
a = np.array([5,2,6,2,7,5,6,8,2,9])
print ('第一个数组：')
print (a)
print ('\n')
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')
print ('我们可以看到每个和原数组下标对应的数值：')
print (a)
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print (indices)
print ('\n')
print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值：
[5 2 6 2 7 5 6 8 2 9]
去重数组的下标：
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


###  numpy的计算（数学函数）

In [40]:
import numpy as np
score = np.array([[80,88],[82,81],[75,81]])
# 1. 获取所有数据最大值
result = np.max(score)
print(result) # 88
# 2. 获取某一个轴上的数据最大值
result = np.max(score,axis=0)
print(result) # [82,88]
# 3. 获取最小值
result = np.min(score)
print(result) # [75,81]
# 4. 获取某一个轴上的数据最小值
result = np.min(score,axis=0)
print(result) # 75
# 5. 数据的比较
result = np.maximum( [-2,-1, 0, 1, 2], 0 ) # 第一个参数中的每一个数与第二个参数比较返回大的
print(result) # [0 0 0 1 2]
result = np.minimum( [-2,-1, 0, 1, 2], 0 ) # 第一个参数中的每一个数与第二个参数比较返回小的
print(result) # [ 2 -1 0 0 0]
result = np.maximum( [-2,-1, 0, 1, 2], [1, 2, 3, 4, 5] )
print(result) # [1 2 3 4 5]
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；

print('\n')

# 6. 求平均值
result = np.mean(score) # 获取所有数据的平均值
print(result)
result = np.mean(score,axis=0) # 获取某一行或者某一列的平均值
print(result)
# 7. 求前缀和
arr = np.array([[1,2,3], [4,5,6]])
# print(arr)
print(arr.cumsum(0))

'''
[1, 2, 3]------> |1 |2 |3 |
[4, 5, 6]------> |5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(1))
'''
[1, 2, 3]------> |1 |2+1 |3+2+1 |
[4, 5, 6]------> |4 |4+5 |4+5+6 |
'''

print('\n')

# 8. argmin 求最小值索引
result = np.argmin(score,axis=0) # [2,1]
res=np.min(score,axis=0) #这样我们就可以知道最小的81是第二排的，是从前往后遍历的,[75,81]
print(result,res)
# print(result)
# print(res)
print('\n')

# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score,axis=0)
print(result)
# 10. 极 值
result = np.ptp(score,axis=None)#就是最大值和最小值的差
print(result)
# 拓展：方差var, 协方差cov, 计算平均值 average, 计算中位数 median


'''通用函数：
numpy.sqrt(array) 平方根函数
numpy.exp(array) e^array[i]的数组
numpy.abs/fabs(array) 计算绝对值
numpy.square(array)
计算各元素的平方 等于array 2
numpy.log/log10/log2(array)
计算各元素的各种对数
numpy.sign(array) 计算各元素正负号
numpy.isnan(array) 计算各元素是否为NaN
numpy.isinf(array) 计算各元素是否为NaN
numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
numpy.modf(array) 将 array 中值得整数和小数分离，作两个数组返回
numpy.ceil(array) 向上取整,也就是取比这个数大的整数
numpy.floor(array) 向下取整,也就是取比这个数小的整数
numpy.rint(array) 四舍五入
numpy.trunc(array) 向 0 取整
numpy.cos(array) 正弦值
numpy.sin(array) 余弦值
numpy.tan(array) 正切值
numpy.add(array1,array2) 元素级加法
numpy.subtract(array1,array2) 元素级减法
numpy.multiply(array1,array2) 元素级乘法
numpy.divide(array1,array2)
元素级除法 array1./array2
numpy.power(array1,array2) 元素级指数 array1.^array2
numpy.maximum/minimum(array1,aray2) 元素级最大值
numpy.fmax/fmin(array1,array2) 元素级最大值，忽略 NaN
numpy.mod(array1,array2) 元素级求模
numpy.copysign(array1,array2) 将第二个数组中值得符号复制给第一个数组中值
numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)
元素级比较运算，产生布尔数组
numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算
'''


88
[82 88]
75
[75 81]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 3 4 5]


81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


[2 1] [75 81]


[2.94392029 3.29983165]
13
