# pandas的两种数据类型

## Series

Pandas有两个最主要也是最重要的数据结构:**Series**和**DataFrame**Series是一种类似于一维数组的**对象**，由一组数据(各种NumPy数据类型)以及一组与之对应的索引(数据标签)组成。

- 类似一维数组的对象

- 由数据和索引组成

  - 索引(index)在左，数据(values)在右

  - 索引是自动创建的

### 1.通过list创建Series

In [11]:
import pandas as pd
# ser_obj = pd.Series(range(10))
#通过list构建
# print(ser_obj)
ser_obj =pd.Series (range(10, 20))

print(ser_obj.head(3))
print('-'*20)
print(ser_obj)
print('-'*20)
print(type(ser_obj))
print('\n')
# print(Series_obj.head(3))
# print('-'*20)
# print(Series_obj)
# print('-'*20)
# print(type(Series_obj))

0    10
1    11
2    12
dtype: int64
--------------------
0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
--------------------
<class 'pandas.Series'>




### 2.获取数据和索引

In [12]:
# ser_obj.index 和ser_obj.values

#获取数据
print(ser_obj.values)
#获取索引
print(ser_obj.index)

[10 11 12 13 14 15 16 17 18 19]
RangeIndex(start=0, stop=10, step=1)


### 3.通过索引获得数据

In [13]:
# ser_obj[idx]

#通过索引获取数据
print(ser_obj[0])
print(ser_obj[8])

10
18


### 4.索引与数据的对应关系不被运算结果影响

In [14]:
#索引与数据的对应关系不被运算结果影响
print(ser_obj * 2)
print(ser_obj > 15)

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


### 5.通过dict构建Series

In [15]:
#通过dict构建Series
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)
print (ser_obj2[2001])

2001    17.8
2002    20.1
2003    16.5
dtype: float64
RangeIndex(start=2001, stop=2004, step=1)
17.8


### 6.name属性

In [16]:
# 对象名:ser_obj.name
# 对象索引名:ser_obj.index.name

# name属性
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
print(ser_obj2.head())

year
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


## DataFrame

<br>DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同型的值。DataFrame既有行索引也有列索引，它可以被看做是由Series组成的字典(共用同一个索引)，数据是以二维结构存放的。
- 类似多维数组/表格数据(如，excel,R中的data.frame)
- 每列数据可以是不同的类型
- 索引包括列索引和行索引

每列数据可以是不同的类型- 索引包括列索引和行索引DataFrame对象既有行索引，又有列索引

行索引，表明不同行，横向索引，叫index，0轴，axis=0

列索引，表名不同列，纵向索引，叫columns，1轴，axis=1

### 1.通过 ndarray 构建 DataFrame

In [19]:
import numpy as np
import pandas as pd
# 通过 ndarray 构建 DataFrame
t = pd. DataFrame (np. arange (12).reshape ((3, 4)))
print (t)
print('-'*20)
array = np.random. randn(5, 4)
print (array)
print('-'*20)
df_obj = pd. DataFrame (array)
print (df_obj. head())

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
--------------------
[[ 0.83304281  0.97951698 -0.90601938  0.02555536]
 [ 1.17108147 -0.52274758 -0.07661383 -0.10180939]
 [-1.05939517 -0.91481924 -0.14489137  1.23353366]
 [ 0.23564283  0.51037229 -0.3989451   0.87443811]
 [ 1.38937994  0.97112227  1.26231854  0.81497034]]
--------------------
          0         1         2         3
0  0.833043  0.979517 -0.906019  0.025555
1  1.171081 -0.522748 -0.076614 -0.101809
2 -1.059395 -0.914819 -0.144891  1.233534
3  0.235643  0.510372 -0.398945  0.874438
4  1.389380  0.971122  1.262319  0.814970
