# Pandas的两种数据类型

## Series

Pandas有两个最主要也是最重要的数据结构:**Series**和**DataFrame**Series是一种类似于一维数组的**对象**，由一组数据(各种NumPy数据类型)以及一组与之对应的索引(数据标签)组成。

- 类似一维数组的对象

- 由数据和索引组成

  - 索引(index)在左，数据(values)在右

  - 索引是自动创建的

### 1.通过list创建Series

In [11]:
import pandas as pd
# ser_obj = pd.Series(range(10))
#通过list构建
# print(ser_obj)
ser_obj =pd.Series (range(10, 20))

print(ser_obj.head(3))
print('-'*20)
print(ser_obj)
print('-'*20)
print(type(ser_obj))
print('\n')
# print(Series_obj.head(3))
# print('-'*20)
# print(Series_obj)
# print('-'*20)
# print(type(Series_obj))

0    10
1    11
2    12
dtype: int64
--------------------
0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
--------------------
<class 'pandas.Series'>




### 2.获取数据和索引

In [12]:
# ser_obj.index 和ser_obj.values

#获取数据
print(ser_obj.values)
#获取索引
print(ser_obj.index)

[10 11 12 13 14 15 16 17 18 19]
RangeIndex(start=0, stop=10, step=1)


### 3.通过索引获得数据

In [13]:
# ser_obj[idx]

#通过索引获取数据
print(ser_obj[0])
print(ser_obj[8])

10
18


### 4.索引与数据的对应关系不被运算结果影响

In [14]:
#索引与数据的对应关系不被运算结果影响
print(ser_obj * 2)
print(ser_obj > 15)

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


### 5.通过dict构建Series

In [15]:
#通过dict构建Series
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)
print (ser_obj2[2001])

2001    17.8
2002    20.1
2003    16.5
dtype: float64
RangeIndex(start=2001, stop=2004, step=1)
17.8


### 6.name属性

In [16]:
# 对象名:ser_obj.name
# 对象索引名:ser_obj.index.name

# name属性
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
print(ser_obj2.head())

year
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


## DataFrame

<br>DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同型的值。DataFrame既有行索引也有列索引，它可以被看做是由Series组成的字典(共用同一个索引)，数据是以二维结构存放的。
- 类似多维数组/表格数据(如，excel,R中的data.frame)
- 每列数据可以是不同的类型
- 索引包括列索引和行索引

每列数据可以是不同的类型- 索引包括列索引和行索引DataFrame对象既有行索引，又有列索引

行索引，表明不同行，横向索引，叫index，0轴，axis=0

列索引，表名不同列，纵向索引，叫columns，1轴，axis=1

### 1.通过 ndarray 构建 DataFrame

In [19]:
import numpy as np
import pandas as pd
# 通过 ndarray 构建 DataFrame
t = pd. DataFrame (np. arange (12).reshape ((3, 4)))
print (t)
print('-'*20)
array = np.random. randn(5, 4)
print (array)
print('-'*20)
df_obj = pd. DataFrame (array)
print (df_obj. head())

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
--------------------
[[ 0.83304281  0.97951698 -0.90601938  0.02555536]
 [ 1.17108147 -0.52274758 -0.07661383 -0.10180939]
 [-1.05939517 -0.91481924 -0.14489137  1.23353366]
 [ 0.23564283  0.51037229 -0.3989451   0.87443811]
 [ 1.38937994  0.97112227  1.26231854  0.81497034]]
--------------------
          0         1         2         3
0  0.833043  0.979517 -0.906019  0.025555
1  1.171081 -0.522748 -0.076614 -0.101809
2 -1.059395 -0.914819 -0.144891  1.233534
3  0.235643  0.510372 -0.398945  0.874438
4  1.389380  0.971122  1.262319  0.814970


### 2.通过dict构建DataFrame

In [27]:
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd. Timestamp ('20190926'),
             'C': pd.Series (1,index=list (range (4)),dtype='float32'),
             'D': np. array ([3] * 4, dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F':'wangdao'}

print(dict_data)
print('-'*20)

df_obj2 = pd. DataFrame (dict_data)
print (df_obj2)
print('-'*20)
d1={"name": ["xiaoming","xiaogang"],
    "age" : [20,32],
    "tel" : [10086,10010]}
print (pd. DataFrame (d1))
print('-'*20)

d2 =[{"name":"xiaohong",
      "age" :32,
      "tel" :10010},
     {"name":"xiaogang",
       "tel":10000},
     {"name":"xiaowang",
       "age":22}]
print (pd. DataFrame (d2))

{'A': 1, 'B': Timestamp('2019-09-26 00:00:00'), 'C': 0    1.0
1    1.0
2    1.0
3    1.0
dtype: float32, 'D': array([3, 3, 3, 3], dtype=int32), 'E': ['Python', 'Java', 'C++', 'C'], 'F': 'wangdao'}
--------------------
   A          B    C  D       E        F
0  1 2019-09-26  1.0  3  Python  wangdao
1  1 2019-09-26  1.0  3    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  3       C  wangdao
--------------------
       name  age    tel
0  xiaoming   20  10086
1  xiaogang   32  10010
--------------------
       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN


### 3.通过列索引获取列数据（Series类型）

In [28]:
# df_obj[col_idx]或 df_obj.col_idx
#通过列索引获取列数据
print(df_obj2['A'])
print('-'*20)

print(type(df_obj2['A']))
print('-'*20)

print(df_obj2.A)

0    1
1    1
2    1
3    1
Name: A, dtype: int64
--------------------
<class 'pandas.Series'>
--------------------
0    1
1    1
2    1
3    1
Name: A, dtype: int64


### 4.增加列数据

In [30]:
# df_obj[new_col_idx]= data类似 Python 的dict 添加 key-value
#增加列
df_obj2['G'] = df_obj2.D+ 4
print (df_obj2.head())

   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  3  Python  wangdao  7
1  1 2019-09-26  1.0  3    Java  wangdao  7
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  3       C  wangdao  7


### 5.删除列

In [31]:
# del df_obj[col_idx]
del(df_obj2['G'])
print(df_obj2.head())

   A          B    C  D       E        F
0  1 2019-09-26  1.0  3  Python  wangdao
1  1 2019-09-26  1.0  3    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  3       C  wangdao


# Pandas的索引操作

## 1.Series和DataFrame中的索引都是Index对象

In [33]:
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd.Timestamp ( '20190926'),
             'C': pd.Series(1,index=list (range (4)),dtype='float32'),
             'D': np.array ([3] * 4, dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F':'window'}
#print dict_data
df_obj2 = pd. DataFrame (dict_data)
ser_obj = pd. Series (range (10, 20))
print (type (ser_obj.index))
print (type (df_obj2. index))
print (df_obj2. index)


<class 'pandas.RangeIndex'>
<class 'pandas.Index'>
Index([0, 1, 2, 3], dtype='int64')


## 2.索引对象不可变，保证了数据的安全

In [34]:
#索引对象不可变(上面代码增加)
df_obj2.index[0] = 2         #会报错

TypeError: Index does not support mutable operations

## 3.常见的index种类

- Index 索引
- Int64Index 整数索引
- MultiIndex 层级索引
- DatetimeIndex 时间戳类型

###  Series索引

#### 1.index指定行索引名

In [36]:
import pandas as pd
ser_obj = pd.Series (range(5), index = ['a', 'b','c','d','e'])
print(ser_obj.head())

ser_obj1 = pd. Series (range (5), index = list ("abcde"))
print (ser_obj1)

a    0
b    1
c    2
d    3
e    4
dtype: int64
a    0
b    1
c    2
d    3
e    4
dtype: int64


#### 2.行索引

In [41]:
# ser_obj['label‘], ser_obj[pos]
#行索引
print(ser_obj.loc['b']) # 索引名
print(ser_obj.iloc[2])  # 索引位置

1
2


#### 3.切片索引

In [42]:
#切片索引
#索引位置取数据，左闭右开
print(ser_obj.iloc[1:3])
#记住索引名左闭右闭
print(ser_obj.loc['b':'d'])

b    1
c    2
dtype: int64
b    1
c    2
d    3
dtype: int64


#### 4.不连续索引

In [43]:
print(ser_obj.iloc[[0, 2, 4]])
print(ser_obj.loc[['a', 'e']])

a    0
c    2
e    4
dtype: int64
a    0
e    4
dtype: int64


#### 5.布尔索引

In [45]:
ser_bool = ser_obj > 2
print(ser_obj)
print(ser_bool)
print('-'*20)
print(ser_obj[ser_bool])
print(ser_obj[ser_obj>2])#取出大于2的元素

a    0
b    1
c    2
d    3
e    4
dtype: int64
a    False
b    False
c    False
d     True
e     True
dtype: bool
--------------------
d    3
e    4
dtype: int64
d    3
e    4
dtype: int64


### DataFrame索引

#### 1.columns指定列索引名

In [46]:
import numpy as np
df_obj = pd.DataFrame(np.random.randn(5,4),
columns= ['a','b','c','d'])
print(df_obj.head())

          a         b         c         d
0 -0.390575 -1.078882 -0.019807  1.372515
1  0.098204 -0.395866 -1.172051 -0.270261
2 -0.131718 -0.527842 -1.402181 -0.732428
3  1.635774  0.320380  0.407299 -0.347555
4 -0.427059 -1.106729 -0.210868 -0.783237


#### 2.列索引

In [47]:
#列索引
print (df_obj['a']) # 返回Series类型
print (df_obj[['a']]) # 返回DataFrame类型
print (type (df_obj[['a']])) # 返回DataFrame 类型

0   -0.390575
1    0.098204
2   -0.131718
3    1.635774
4   -0.427059
Name: a, dtype: float64
          a
0 -0.390575
1  0.098204
2 -0.131718
3  1.635774
4 -0.427059
<class 'pandas.DataFrame'>


In [50]:
#列索引
print(df_obj.loc[:,'a']) # 返回Series类型print('-'*50)
print(df_obj.loc[:,['a']]) #返回DataFrame类型print('-'*50)
print(type(df_obj.loc[:,['a']])) #返回DataFrame类型

0   -0.390575
1    0.098204
2   -0.131718
3    1.635774
4   -0.427059
Name: a, dtype: float64
          a
0 -0.390575
1  0.098204
2 -0.131718
3  1.635774
4 -0.427059
<class 'pandas.DataFrame'>


In [54]:
print(df_obj.loc[1,['a']])
# 取一行
print(df_obj.loc[1,:])

a    0.098204
Name: 1, dtype: float64
a    0.098204
b   -0.395866
c   -1.172051
d   -0.270261
Name: 1, dtype: float64


#### 3.不连续索引

In [59]:
#标签索loc，建议使用Loc，效率更高#Series
print(ser_obj)
print(ser_obj.loc['b':'d'])#前闭后闭
# print('-'*50)

a    0
b    1
c    2
d    3
e    4
dtype: int64
b    1
c    2
d    3
dtype: int64


In [62]:
# DataFrame
df_obj = pd.DataFrame (np.random.randn(5,4),columns = list('abcd'),index=list('abcde'))
print(df_obj)
print('-'*20)

print(df_obj.loc['a']) #拿的是行
print('-'*20)

# 第一个参数索引行，第二个参数是列，loc或者iloc效率高于直接用取下标的方式，前闭后闭
print(df_obj.loc['a':'c','b':'d'])
print('-'*20)

#连续索引
print(df_obj.loc[['a','c'],['b','d']])
print('-'*20)

#不连续索引
print(df_obj.loc[['c'],['b']])
print('-'*20)

#取一个值，返回的是DataFrame类型
print(df_obj.loc['c','b']) #取一个值

          a         b         c         d
a  0.210433  0.781592  0.031278 -1.854185
b -1.229987  2.609388  0.090618 -1.844172
c  0.179721  1.483153  0.869993  0.576816
d -0.049778 -1.176533 -0.465775  2.638268
e -1.212746  0.104807  1.102505  0.786969
--------------------
a    0.210433
b    0.781592
c    0.031278
d   -1.854185
Name: a, dtype: float64
--------------------
          b         c         d
a  0.781592  0.031278 -1.854185
b  2.609388  0.090618 -1.844172
c  1.483153  0.869993  0.576816
--------------------
          b         d
a  0.781592 -1.854185
c  1.483153  0.576816
--------------------
          b
c  1.483153
--------------------
1.4831532734292279


#### 4.loc标签索引

In [63]:
# DataFrame
df_obj = pd.DataFrame (np.random.randn(5,4),columns = list('abcd'),index=list('abcde'))
print(df_obj)
print('-'*20)

print(df_obj.loc['a']) #拿的是行
print('-'*20)

# 第一个参数索引行，第二个参数是列，loc或者iloc效率高于直接用取下标的方式，前闭后闭
print(df_obj.loc['a':'c','b':'d'])
print('-'*20)

#连续索引
print(df_obj.loc[['a','c'],['b','d']])
print('-'*20)

#不连续索引
print(df_obj.loc[['c'],['b']])
print('-'*20)

#取一个值，返回的是DataFrame类型
print(df_obj.loc['c','b']) #取一个值

          a         b         c         d
a  0.552257 -1.006200 -1.395008 -1.810977
b -1.355851 -1.944844  0.853137  1.747374
c -0.306992 -0.662509  0.304225 -0.397078
d  0.171786  0.485094 -0.087876  0.328529
e  0.186320 -0.994664 -0.160916  0.240780
--------------------
a    0.552257
b   -1.006200
c   -1.395008
d   -1.810977
Name: a, dtype: float64
--------------------
          b         c         d
a -1.006200 -1.395008 -1.810977
b -1.944844  0.853137  1.747374
c -0.662509  0.304225 -0.397078
--------------------
          b         d
a -1.006200 -1.810977
c -0.662509 -0.397078
--------------------
          b
c -0.662509
--------------------
-0.6625094666351831


#### 5.iloc位置索引

In [65]:
# Series
print(ser_obj[1:3])
print(ser_obj.iloc[1:3]) # 前闭后开[)，效率高print('-'*50)
print('-'*20)

#DataFrame，iloc是前闭后开[)
print(df_obj)
print('-'*20)

print(df_obj.iloc[0:2,0:2]) # 注意和df_obj.loc[0:2,'a']的区别
print('-'*20)

print(df_obj.iloc[[0,2],[0,2]])
print('-'*20)
# 不连续索引
print(df_obj.iloc[0,0]) # 取一个值

b    1
c    2
dtype: int64
b    1
c    2
dtype: int64
--------------------
          a         b         c         d
a  0.552257 -1.006200 -1.395008 -1.810977
b -1.355851 -1.944844  0.853137  1.747374
c -0.306992 -0.662509  0.304225 -0.397078
d  0.171786  0.485094 -0.087876  0.328529
e  0.186320 -0.994664 -0.160916  0.240780
--------------------
          a         b
a  0.552257 -1.006200
b -1.355851 -1.944844
--------------------
          a         c
a  0.552257 -1.395008
c -0.306992  0.304225
--------------------
0.5522569050093331


# Pandas的对齐运算

是数据清洗的重要过程，可以按索引对齐进行运算，如果没对齐的位置则补NaN，最后也可以填充NaN

In [67]:
a=np.array([1,2,3,4,5])
b=np.array([1])
print(a+b)

[2 3 4 5 6]


In [66]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3])
print(a+b)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [68]:
import pandas as pd
s1 = pd.Series(range(10, 20), index = range(10))
s2 = pd.Series(range(20, 25), index = range(5))
# Series 对齐运算
print('sl+s2: ')
s3=s1+s2
print(s3)#缺失数据默认是NaN np.nan

sl+s2: 
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64


In [73]:
print(np.isnan(s3[6]))
print('-'*20)

print(s3)
print('-'*20)

print(s1)
print('-'*20)

print(s2)
print('-'*20)

print(s2.add(s1, fill_value = 0)) #未对齐的数据将和填充值做运算
print('-'*20)

print(s2.sub(s1, fill_value = 0))

True
--------------------
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64
--------------------
0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
--------------------
0    20
1    21
2    22
3    23
4    24
dtype: int64
--------------------
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64
--------------------
0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
5   -15.0
6   -16.0
7   -17.0
8   -18.0
9   -19.0
dtype: float64


In [74]:
#df的对齐运算
import numpy as np
df1 = pd.DataFrame(np.ones((2,2)),columns = ['a', 'b'])
df2 = pd.DataFrame(np.ones((3,3)), columns = ['a', 'b', 'c'])
print(df1)
print(df2)
print('-'*50)
print(df2.dtypes)
print(df1-df2)
print(df2.sub(df1,fill_value=2))#未对齐的数据将和填充值做运算

     a    b
0  1.0  1.0
1  1.0  1.0
     a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
--------------------------------------------------
a    float64
b    float64
c    float64
dtype: object
     a    b   c
0  0.0  0.0 NaN
1  0.0  0.0 NaN
2  NaN  NaN NaN
     a    b    c
0  0.0  0.0 -1.0
1  0.0  0.0 -1.0
2 -1.0 -1.0 -1.0


# Pandas的函数应用

## 1.Pandas的索引排序

In [6]:
# Series
import pandas as pd
import numpy as np
print(np.random.randint(5, size=5))
s4 = pd.Series(range(10, 15), index = np.random.randint(5,size=5)) #索引随机生成
print(s4)
print('-'*50)
#索引排序,sort_index返回一个新的排好索引的series
print(s4.sort_index())
print('-'*50)
print(s4)
#s4.loc[0:3] loc索引值不唯一时直接报错
print(s4.iloc[0:3])
print('-'*50)
s4[0:3] #默认用的位置索引

[0 4 4 3 1]
4    10
0    11
3    12
1    13
3    14
dtype: int64
--------------------------------------------------
0    11
1    13
3    12
3    14
4    10
dtype: int64
--------------------------------------------------
4    10
0    11
3    12
1    13
3    14
dtype: int64
4    10
0    11
3    12
dtype: int64
--------------------------------------------------


4    10
0    11
3    12
dtype: int64

In [11]:
# DataFrame
df4 = pd.DataFrame (np.random.randn(5, 5),
                    index=np.random.randint(5, size=5),
                    columns=np.random.randint(5, size=5))
print(df4)
#轴零是行索引排序
df4_isort = df4.sort_index(axis=0, ascending=False)
print(df4_isort)
print('-'*50)

df4_isort = df4.sort_index(axis=0, ascending=True)
print(df4_isort)
print('-'*50)

df4_isort = df4.sort_index(axis=1, ascending=True)
print(df4_isort)

          3         0         4         3         0
0  0.799488 -0.485683 -1.935161 -1.154522 -0.835997
4 -1.288452 -2.520201 -0.418128 -0.153425 -1.265740
0 -0.392068 -1.419433 -0.880666 -0.159835  0.774378
3 -1.622486 -0.587531 -1.421167  1.397395  0.214698
3  0.728144  0.970934 -1.148124  1.437742  0.137786
          3         0         4         3         0
4 -1.288452 -2.520201 -0.418128 -0.153425 -1.265740
3  0.728144  0.970934 -1.148124  1.437742  0.137786
3 -1.622486 -0.587531 -1.421167  1.397395  0.214698
0  0.799488 -0.485683 -1.935161 -1.154522 -0.835997
0 -0.392068 -1.419433 -0.880666 -0.159835  0.774378
--------------------------------------------------
          3         0         4         3         0
0  0.799488 -0.485683 -1.935161 -1.154522 -0.835997
0 -0.392068 -1.419433 -0.880666 -0.159835  0.774378
3 -1.622486 -0.587531 -1.421167  1.397395  0.214698
3  0.728144  0.970934 -1.148124  1.437742  0.137786
4 -1.288452 -2.520201 -0.418128 -0.153425 -1.265740
-------------