# pandas的两种数据类型

## Series

Pandas有两个最主要也是最重要的数据结构:**Series**和**DataFrame**Series是一种类似于一维数组的**对象**，由一组数据(各种NumPy数据类型)以及一组与之对应的索引(数据标签)组成。

- 类似一维数组的对象

- 由数据和索引组成

  - 索引(index)在左，数据(values)在右

  - 索引是自动创建的

### 1.通过list创建Series

In [11]:
import pandas as pd
# ser_obj = pd.Series(range(10))
#通过list构建
# print(ser_obj)
ser_obj =pd.Series (range(10, 20))

print(ser_obj.head(3))
print('-'*20)
print(ser_obj)
print('-'*20)
print(type(ser_obj))
print('\n')
# print(Series_obj.head(3))
# print('-'*20)
# print(Series_obj)
# print('-'*20)
# print(type(Series_obj))

0    10
1    11
2    12
dtype: int64
--------------------
0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
--------------------
<class 'pandas.Series'>




### 2.获取数据和索引

In [12]:
# ser_obj.index 和ser_obj.values

#获取数据
print(ser_obj.values)
#获取索引
print(ser_obj.index)

[10 11 12 13 14 15 16 17 18 19]
RangeIndex(start=0, stop=10, step=1)


### 3.通过索引获得数据

In [13]:
# ser_obj[idx]

#通过索引获取数据
print(ser_obj[0])
print(ser_obj[8])

10
18


### 4.索引与数据的对应关系不被运算结果影响

In [14]:
#索引与数据的对应关系不被运算结果影响
print(ser_obj * 2)
print(ser_obj > 15)

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


### 5.通过dict构建Series

In [15]:
#通过dict构建Series
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)
print (ser_obj2[2001])

2001    17.8
2002    20.1
2003    16.5
dtype: float64
RangeIndex(start=2001, stop=2004, step=1)
17.8


### 6.name属性

In [16]:
# 对象名:ser_obj.name
# 对象索引名:ser_obj.index.name

# name属性
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
print(ser_obj2.head())

year
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


## DataFrame

<br>DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同型的值。DataFrame既有行索引也有列索引，它可以被看做是由Series组成的字典(共用同一个索引)，数据是以二维结构存放的。
- 类似多维数组/表格数据(如，excel,R中的data.frame)
- 每列数据可以是不同的类型
- 索引包括列索引和行索引

每列数据可以是不同的类型- 索引包括列索引和行索引DataFrame对象既有行索引，又有列索引

行索引，表明不同行，横向索引，叫index，0轴，axis=0

列索引，表名不同列，纵向索引，叫columns，1轴，axis=1

### 1.通过 ndarray 构建 DataFrame

In [19]:
import numpy as np
import pandas as pd
# 通过 ndarray 构建 DataFrame
t = pd. DataFrame (np. arange (12).reshape ((3, 4)))
print (t)
print('-'*20)
array = np.random. randn(5, 4)
print (array)
print('-'*20)
df_obj = pd. DataFrame (array)
print (df_obj. head())

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
--------------------
[[ 0.83304281  0.97951698 -0.90601938  0.02555536]
 [ 1.17108147 -0.52274758 -0.07661383 -0.10180939]
 [-1.05939517 -0.91481924 -0.14489137  1.23353366]
 [ 0.23564283  0.51037229 -0.3989451   0.87443811]
 [ 1.38937994  0.97112227  1.26231854  0.81497034]]
--------------------
          0         1         2         3
0  0.833043  0.979517 -0.906019  0.025555
1  1.171081 -0.522748 -0.076614 -0.101809
2 -1.059395 -0.914819 -0.144891  1.233534
3  0.235643  0.510372 -0.398945  0.874438
4  1.389380  0.971122  1.262319  0.814970


### 2.通过dict构建DataFrame

In [27]:
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd. Timestamp ('20190926'),
             'C': pd.Series (1,index=list (range (4)),dtype='float32'),
             'D': np. array ([3] * 4, dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F':'wangdao'}

print(dict_data)
print('-'*20)

df_obj2 = pd. DataFrame (dict_data)
print (df_obj2)
print('-'*20)
d1={"name": ["xiaoming","xiaogang"],
    "age" : [20,32],
    "tel" : [10086,10010]}
print (pd. DataFrame (d1))
print('-'*20)

d2 =[{"name":"xiaohong",
      "age" :32,
      "tel" :10010},
     {"name":"xiaogang",
       "tel":10000},
     {"name":"xiaowang",
       "age":22}]
print (pd. DataFrame (d2))

{'A': 1, 'B': Timestamp('2019-09-26 00:00:00'), 'C': 0    1.0
1    1.0
2    1.0
3    1.0
dtype: float32, 'D': array([3, 3, 3, 3], dtype=int32), 'E': ['Python', 'Java', 'C++', 'C'], 'F': 'wangdao'}
--------------------
   A          B    C  D       E        F
0  1 2019-09-26  1.0  3  Python  wangdao
1  1 2019-09-26  1.0  3    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  3       C  wangdao
--------------------
       name  age    tel
0  xiaoming   20  10086
1  xiaogang   32  10010
--------------------
       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN


### 3.通过列索引获取列数据（Series类型）

In [28]:
# df_obj[col_idx]或 df_obj.col_idx
#通过列索引获取列数据
print(df_obj2['A'])
print('-'*20)

print(type(df_obj2['A']))
print('-'*20)

print(df_obj2.A)

0    1
1    1
2    1
3    1
Name: A, dtype: int64
--------------------
<class 'pandas.Series'>
--------------------
0    1
1    1
2    1
3    1
Name: A, dtype: int64


### 4.增加列数据

In [30]:
# df_obj[new_col_idx]= data类似 Python 的dict 添加 key-value
#增加列
df_obj2['G'] = df_obj2.D+ 4
print (df_obj2.head())

   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  3  Python  wangdao  7
1  1 2019-09-26  1.0  3    Java  wangdao  7
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  3       C  wangdao  7


### 5.删除列

In [31]:
# del df_obj[col_idx]
del(df_obj2['G'])
print(df_obj2.head())

   A          B    C  D       E        F
0  1 2019-09-26  1.0  3  Python  wangdao
1  1 2019-09-26  1.0  3    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  3       C  wangdao


# Pandas的索引操作

## 1.Series和DataFrame中的索引都是Index对象

In [33]:
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd.Timestamp ( '20190926'),
             'C': pd.Series(1,index=list (range (4)),dtype='float32'),
             'D': np.array ([3] * 4, dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F':'window'}
#print dict_data
df_obj2 = pd. DataFrame (dict_data)
ser_obj = pd. Series (range (10, 20))
print (type (ser_obj.index))
print (type (df_obj2. index))
print (df_obj2. index)


<class 'pandas.RangeIndex'>
<class 'pandas.Index'>
Index([0, 1, 2, 3], dtype='int64')


## 2.索引对象不可变，保证了数据的安全

In [34]:
#索引对象不可变(上面代码增加)
df_obj2.index[0] = 2         #会报错

TypeError: Index does not support mutable operations

## 3.常见的index种类

- Index 索引
- Int64Index 整数索引
- MultiIndex 层级索引
- DatetimeIndex 时间戳类型

###  Series索引

#### 1.index指定行索引名

In [36]:
import pandas as pd
ser_obj = pd.Series (range(5), index = ['a', 'b','c','d','e'])
print(ser_obj.head())

ser_obj1 = pd. Series (range (5), index = list ("abcde"))
print (ser_obj1)

a    0
b    1
c    2
d    3
e    4
dtype: int64
a    0
b    1
c    2
d    3
e    4
dtype: int64


#### 2.行索引

In [41]:
# ser_obj['label‘], ser_obj[pos]
#行索引
print(ser_obj.loc['b']) # 索引名
print(ser_obj.iloc[2])  # 索引位置

1
2


#### 3.切片索引

In [42]:
#切片索引
#索引位置取数据，左闭右开
print(ser_obj.iloc[1:3])
#记住索引名左闭右闭
print(ser_obj.loc['b':'d'])

b    1
c    2
dtype: int64
b    1
c    2
d    3
dtype: int64


#### 4.不连续索引

In [43]:
print(ser_obj.iloc[[0, 2, 4]])
print(ser_obj.loc[['a', 'e']])

a    0
c    2
e    4
dtype: int64
a    0
e    4
dtype: int64


#### 5.布尔索引

In [45]:
ser_bool = ser_obj > 2
print(ser_obj)
print(ser_bool)
print('-'*20)
print(ser_obj[ser_bool])
print(ser_obj[ser_obj>2])#取出大于2的元素

a    0
b    1
c    2
d    3
e    4
dtype: int64
a    False
b    False
c    False
d     True
e     True
dtype: bool
--------------------
d    3
e    4
dtype: int64
d    3
e    4
dtype: int64


### DataFrame索引

#### 1.columns指定列索引名

In [46]:
import numpy as np
df_obj = pd.DataFrame(np.random.randn(5,4),
columns= ['a','b','c','d'])
print(df_obj.head())

          a         b         c         d
0 -0.390575 -1.078882 -0.019807  1.372515
1  0.098204 -0.395866 -1.172051 -0.270261
2 -0.131718 -0.527842 -1.402181 -0.732428
3  1.635774  0.320380  0.407299 -0.347555
4 -0.427059 -1.106729 -0.210868 -0.783237


#### 2.列索引

In [47]:
#列索引
print (df_obj['a']) # 返回Series类型
print (df_obj[['a']]) # 返回DataFrame类型
print (type (df_obj[['a']])) # 返回DataFrame 类型

0   -0.390575
1    0.098204
2   -0.131718
3    1.635774
4   -0.427059
Name: a, dtype: float64
          a
0 -0.390575
1  0.098204
2 -0.131718
3  1.635774
4 -0.427059
<class 'pandas.DataFrame'>
